new translations + alternc_reload fix

diff --git a/src/alternc_reload b/src/alternc_reload
--- a/src/alternc_reload
+++ b/src/alternc_reload
@@ -76,7 +76,7 @@ if [ ! -z "$RELOAD_ZONES" ]; then
         apache_reload
         ;;
       *)
-        $sudo rndc reload || echo "Cannot reload bind for zone $zone" 
+        $sudo rndc reload "$zone" || echo "Cannot reload bind for zone $zone" 
         ;;
     esac
   done
